/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import config.config;
import static config.config.connectDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ListPackages extends javax.swing.JFrame {

   private DefaultTableModel model;
    public ListPackages() {
        
        initComponents();
        
        model = (DefaultTableModel) table_packages.getModel(); // ✅ FIX
        loadPackages();
        displayPackage();
         table_packages.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
         setTitle("Packages");
      
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        JLabel lbl = new JLabel("Packages Page");
        lbl.setHorizontalAlignment(SwingConstants.CENTER);

        add(lbl);
    }
 private void loadPackages() {
    model.setRowCount(0); // clear table first

    String sql = "SELECT * FROM tbl_packages";

    try (Connection conn = config.connectDB();
         PreparedStatement pst = conn.prepareStatement(sql);
         ResultSet rs = pst.executeQuery()) {

       while (rs.next()) {
    model.addRow(new Object[]{
        rs.getInt("p_id"),
        rs.getString("package_name"),
        rs.getDouble("price"),
        rs.getInt("pax"),           // ✅ ADDED
        rs.getString("description")
    });
}

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}

   void displayPackage() {
           config conf = new config();
           String sql = "SELECT p_id, package_name, price, description, pax, status FROM tbl_packages";
           conf.displayUser(sql, table_packages);
           
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jPanel1 = new javax.swing.JPanel();
        jpanel = new javax.swing.JPanel();
        Packages = new javax.swing.JButton();
        Reservations = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jButtondashboard = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_packages = new javax.swing.JTable();
        jButtonreserved = new javax.swing.JButton();
        jButtonviewReservation = new javax.swing.JButton();
        jButtonsearch = new javax.swing.JButton();
        jTextFieldbar = new javax.swing.JTextField();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanel.setBackground(new java.awt.Color(0, 0, 0));
        jpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpanelMouseClicked(evt);
            }
        });
        jpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Packages.setBackground(new java.awt.Color(0, 153, 153));
        Packages.setText("Packages");
        Packages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PackagesMouseClicked(evt);
            }
        });
        Packages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PackagesActionPerformed(evt);
            }
        });
        jpanel.add(Packages, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 140, -1));

        Reservations.setBackground(new java.awt.Color(0, 153, 153));
        Reservations.setText("Reservations");
        Reservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservationsActionPerformed(evt);
            }
        });
        jpanel.add(Reservations, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 140, -1));

        Logout.setBackground(new java.awt.Color(0, 153, 153));
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jpanel.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 140, -1));

        jButtondashboard.setBackground(new java.awt.Color(0, 153, 153));
        jButtondashboard.setText("Dashboard");
        jButtondashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondashboardActionPerformed(evt);
            }
        });
        jpanel.add(jButtondashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 140, -1));

        profile.setBackground(new java.awt.Color(0, 153, 153));
        profile.setText("Profile");
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        jpanel.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 140, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/redefined.png"))); // NOI18N
        jLabel2.setOpaque(true);
        jpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 150));

        jPanel1.add(jpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 510));

        table_packages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table_packages);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, 190));

        jButtonreserved.setBackground(new java.awt.Color(0, 204, 204));
        jButtonreserved.setText("Reserved");
        jButtonreserved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonreservedActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonreserved, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        jButtonviewReservation.setBackground(new java.awt.Color(0, 204, 204));
        jButtonviewReservation.setText("View Reservations");
        jButtonviewReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonviewReservationActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonviewReservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jButtonsearch.setBackground(new java.awt.Color(0, 204, 204));
        jButtonsearch.setText("Search");
        jButtonsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsearchActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));
        jPanel1.add(jTextFieldbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PackagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PackagesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PackagesMouseClicked

    private void PackagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PackagesActionPerformed
        ListPackages lkg = new ListPackages();
        lkg.setVisible(true);
        lkg.pack();
        lkg.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_PackagesActionPerformed

    private void ReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservationsActionPerformed
       // Open ViewReservationTable for current user
    ViewReservationTable rsv = new ViewReservationTable();
    rsv.setVisible(true);
    rsv.pack();
    rsv.setLocationRelativeTo(null);
    this.dispose();        
    }//GEN-LAST:event_ReservationsActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (choice == JOptionPane.YES_OPTION) {

            // ✅ Clear session data
            Session.u_id = 0;
            Session.fullname = null;
            Session.type = null;

            // ✅ Go back to login
            LoginForm lgf = new LoginForm();
            lgf.setVisible(true);
            lgf.pack();
            lgf.setLocationRelativeTo(null);

            // ✅ Close current window
            this.dispose();
        }
    }//GEN-LAST:event_LogoutActionPerformed

    private void jButtondashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondashboardActionPerformed
        Dashboard db = new Dashboard();
        db.setVisible(true);
        db.pack();
        db.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButtondashboardActionPerformed

    private void jpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jpanelMouseClicked

    private void jButtonreservedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonreservedActionPerformed
      int row = table_packages.getSelectedRow();

if (row == -1) {
    JOptionPane.showMessageDialog(this, "Select a package first.");
    return;
}

int packageId = (int) table_packages.getValueAt(row, 0);

ReservationForm rf = new ReservationForm(this, true, packageId);
rf.setVisible(true);



    }//GEN-LAST:event_jButtonreservedActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        UsersProfile pf = new UsersProfile();
        pf.setVisible(true);
        pf.pack();
        pf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_profileActionPerformed

    private void jButtonviewReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonviewReservationActionPerformed
            // Open ViewReservationTable for current user
    ViewReservationTable rsv = new ViewReservationTable();
    rsv.setVisible(true);
    rsv.pack();
    rsv.setLocationRelativeTo(null);
    this.dispose();       
    }//GEN-LAST:event_jButtonviewReservationActionPerformed

    private void jButtonsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsearchActionPerformed
         String keyword = jTextFieldbar.getText().trim();

    if (keyword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter something to search!");
        return;
    }

    config conf = new config();
   String sql =
"SELECT p_id, package_name, price, pax, description, status FROM tbl_packages " +
"WHERE package_name LIKE '%" + keyword + "%' " +
"OR price LIKE '%" + keyword + "%' " +
"OR pax LIKE '%" + keyword + "%' " +
"OR description LIKE '%" + keyword + "%' " +
"OR status LIKE '%" + keyword + "%'";


    conf.displayUser(sql, table_packages);
    }//GEN-LAST:event_jButtonsearchActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // 🔐 CHECK LOGIN FIRST
    if (Session.u_id == 0) {

        JOptionPane.showMessageDialog(this, "Please login first!");

        // Open login form
        LoginForm login = new LoginForm();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);

        // Close this dashboard immediately
        this.dispose();
        return;
    }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListPackages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListPackages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListPackages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListPackages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListPackages().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton Packages;
    private javax.swing.JButton Reservations;
    private javax.swing.JButton jButtondashboard;
    private javax.swing.JButton jButtonreserved;
    private javax.swing.JButton jButtonsearch;
    private javax.swing.JButton jButtonviewReservation;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldbar;
    private javax.swing.JPanel jpanel;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JButton profile;
    private javax.swing.JTable table_packages;
    // End of variables declaration//GEN-END:variables
}

