/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import config.config;
import static config.config.connectDB;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class packageformdialog extends javax.swing.JDialog {

   private int packageId = 0;
    public packageformdialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
    loadPackageData();
    
    }

   

  
    public void setPackageData(int id, String name, String p_price, String desc, String status) {
    this.packageId = id;

    package_name1.setText(name);
    price.setText(p_price);
    description.setText(desc);
    jComboBoxstatus.setSelectedItem(status);
}

    
   private void loadPackageData() {
    try {
        Connection conn = config.connectDB();
        String sql = "SELECT * FROM tbl_packages WHERE p_id = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, packageId);

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
              package_name1.setText(rs.getString("package_name"));
            price.setText(rs.getString("price"));
            description.setText(rs.getString("description"));
            jComboBoxstatus.setSelectedItem(rs.getString("status"));
        }

        conn.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
   public void setFormMode(int id) {
    this.packageId = id;

    if (packageId == 0) {
        jLabel.setText("ADD PACKAGE");
        clearForm();
    } else {
        jLabel.setText("UPDATE PACKAGE");
        loadPackageData(packageId);
    }
}


    private void loadStatus() {
    jComboBoxstatus.removeAllItems();
    jComboBoxstatus.addItem("Available");
    jComboBoxstatus.addItem("Not Available");
}
    private void loadPackageData(int id) {
    String sql = "SELECT * FROM tbl_packages WHERE p_id=?";

    try (Connection con = config.connectDB();
         PreparedStatement pst = con.prepareStatement(sql)) {

        pst.setInt(1, id);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            package_name1.setText(rs.getString("package_name"));
            price.setText(rs.getString("price"));
            description.setText(rs.getString("description"));
            jComboBoxstatus.setSelectedItem(rs.getString("status"));
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}

   private void clearForm() {
    package_name1.setText("");
    price.setText("");
    description.setText("");
    jComboBoxstatus.setSelectedIndex(0);
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelp_image = new javax.swing.JLabel();
        package_name1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxstatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Price:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 40, -1));

        jLabelp_image.setBackground(new java.awt.Color(255, 255, 255));
        jLabelp_image.setOpaque(true);
        jLabelp_image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelp_imageMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelp_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 170, 120));
        jPanel1.add(package_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 170, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Picture:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 170, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("status:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 70, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("description:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 70, 30));

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel.setText("ADD PACKAGE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 190, 40));

        description.setColumns(20);
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 180, 70));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Package Name:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jComboBoxstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Not Available", " " }));
        jComboBoxstatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxstatusMouseClicked(evt);
            }
        });
        jComboBoxstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxstatusActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
      try {
        Connection conn = connectDB();

        String name = package_name1.getText();
        double p_price = Double.parseDouble(price.getText());
        String desc = description.getText();
        String status = jComboBoxstatus.getSelectedItem().toString();

        String sql;

        if (packageId == 0) {
            // ADD
            sql = "INSERT INTO tbl_packages (package_name, price, description, status) VALUES (?, ?, ?, ?)";
        } else {
            // UPDATE
            sql = "UPDATE tbl_packages SET package_name=?, price=?, description=?, status=? WHERE p_id=?";
        }

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, name);
        pst.setDouble(2, p_price);
        pst.setString(3, desc);
        pst.setString(4, status);

        if (packageId != 0) {
            pst.setInt(5, packageId);
        }

        pst.executeUpdate();
        conn.close();

        JOptionPane.showMessageDialog(this,
                packageId == 0 ? "Package added successfully!" : "Package updated successfully!");

        this.dispose();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jLabelp_imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelp_imageMouseClicked
         JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select Profile Picture");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
            "Image files", "jpg", "jpeg", "png", "gif"
        ));

        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            ImageIcon icon = new ImageIcon(selectedFile.getAbsolutePath());

            // Scale image to fit JLabel
            Image img = icon.getImage().getScaledInstance(
                    jLabelp_image.getWidth(),
                    jLabelp_image.getHeight(),
                    Image.SCALE_SMOOTH
            );
            jLabelp_image.setIcon(new ImageIcon(img));
        }
    }//GEN-LAST:event_jLabelp_imageMouseClicked

    private void jComboBoxstatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxstatusMouseClicked
       
    }//GEN-LAST:event_jComboBoxstatusMouseClicked

    private void jComboBoxstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxstatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(packageformdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(packageformdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(packageformdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(packageformdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                packageformdialog dialog = new packageformdialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea description;
    private javax.swing.JComboBox<String> jComboBoxstatus;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelp_image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField package_name1;
    private javax.swing.JTextField price;
    // End of variables declaration//GEN-END:variables
}
