/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import config.config;
import static config.config.connectDB;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class PackagesTable extends javax.swing.JFrame {

    
    private DefaultTableModel model;
    

    public PackagesTable() {
        initComponents();
      
         model = (DefaultTableModel) table_package.getModel(); // ✅ FIX

    displayPackage();
   
       
        loadPackages();
        table_package.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
         setTitle("Packages");
        
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        JLabel lbl = new JLabel("Packages Page");
        lbl.setHorizontalAlignment(SwingConstants.CENTER);

        add(lbl);
    }
   void displayPackage() {
    config conf = new config();
    String sql = "SELECT p_id, package_name, price, pax, description, status FROM tbl_packages";
    conf.displayUser(sql, table_package);  // Make sure displayUser also handles the Pax column
}

   
    
  private void loadPackages() {
    try {
        Connection conn = connectDB();
        PreparedStatement pst = conn.prepareStatement("SELECT * FROM tbl_packages");
        ResultSet rs = pst.executeQuery();

        model.setRowCount(0);
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("p_id"),
                rs.getString("package_name"),
                rs.getDouble("price"),
                rs.getInt("pax"),  // NEW
                rs.getString("description"),
                rs.getString("status")
            });
        }

        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        jButton4Packages = new javax.swing.JButton();
        jButton5dashboard = new javax.swing.JButton();
        jButton3Reservations = new javax.swing.JButton();
        jButton1ViewUsers = new javax.swing.JButton();
        UserProfile = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_package = new javax.swing.JTable();
        addPackage = new javax.swing.JButton();
        editpackage = new javax.swing.JButton();
        deletepackage = new javax.swing.JButton();
        jTextFieldSearchbar = new javax.swing.JTextField();
        jButtonClicksearch = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setBackground(new java.awt.Color(0, 153, 153));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel2.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 140, -1));

        jButton4Packages.setBackground(new java.awt.Color(0, 153, 153));
        jButton4Packages.setText("Packages");
        jButton4Packages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4PackagesActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4Packages, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 140, -1));

        jButton5dashboard.setBackground(new java.awt.Color(0, 153, 153));
        jButton5dashboard.setText("Dashboard");
        jButton5dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5dashboardActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 140, -1));

        jButton3Reservations.setBackground(new java.awt.Color(0, 153, 153));
        jButton3Reservations.setText("Reservations");
        jButton3Reservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ReservationsActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3Reservations, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 140, -1));

        jButton1ViewUsers.setBackground(new java.awt.Color(0, 153, 153));
        jButton1ViewUsers.setText("View Users");
        jButton1ViewUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ViewUsersActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1ViewUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 140, -1));

        UserProfile.setBackground(new java.awt.Color(0, 153, 153));
        UserProfile.setText("Profile");
        UserProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserProfileActionPerformed(evt);
            }
        });
        jPanel2.add(UserProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 140, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/redefined.png"))); // NOI18N
        jLabel2.setOpaque(true);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 150));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 540));

        table_package.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table_package);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 580, -1));

        addPackage.setBackground(new java.awt.Color(0, 204, 204));
        addPackage.setText("Add Package");
        addPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPackageActionPerformed(evt);
            }
        });
        jPanel1.add(addPackage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        editpackage.setBackground(new java.awt.Color(0, 204, 204));
        editpackage.setText("Edit Package");
        editpackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editpackageActionPerformed(evt);
            }
        });
        jPanel1.add(editpackage, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        deletepackage.setBackground(new java.awt.Color(0, 204, 204));
        deletepackage.setText("Delete Package");
        deletepackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletepackageActionPerformed(evt);
            }
        });
        jPanel1.add(deletepackage, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        jTextFieldSearchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchbarActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldSearchbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 150, -1));

        jButtonClicksearch.setText("Search");
        jButtonClicksearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClicksearchActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClicksearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (choice == JOptionPane.YES_OPTION) {

            // ✅ Clear session data
            Session.u_id = 0;
            Session.fullname = null;
            Session.type = null;

            // ✅ Go back to login
            LoginForm lgf = new LoginForm();
            lgf.setVisible(true);
            lgf.pack();
            lgf.setLocationRelativeTo(null);

            // ✅ Close current window
            this.dispose();
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void jButton4PackagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4PackagesActionPerformed
        PackagesTable pg = new PackagesTable();
        pg.setVisible(true);
        pg.pack();
        pg.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton4PackagesActionPerformed

    private void jButton5dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5dashboardActionPerformed
        // Already on dashboard
    }//GEN-LAST:event_jButton5dashboardActionPerformed

    private void addPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPackageActionPerformed
      packageformdialog pfd = new packageformdialog(this, true);    
      pfd.setVisible(true);
    

    // AUTO refresh when dialog closes
    displayPackage();
    }//GEN-LAST:event_addPackageActionPerformed

    private void editpackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editpackageActionPerformed
      int row = table_package.getSelectedRow();

if (row == -1) {
    JOptionPane.showMessageDialog(this, "Please select a package first!");
    return;
}

int packageId = Integer.parseInt(table_package.getValueAt(row, 0).toString());

packageformdialog form = new packageformdialog(this, true);
form.setFormMode(packageId);
form.setVisible(true);

displayPackage();

    }//GEN-LAST:event_editpackageActionPerformed

    private void deletepackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletepackageActionPerformed
       int row = table_package.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a package to delete!");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this package?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        try {
            Connection conn = connectDB();
            int id = Integer.parseInt(table_package.getValueAt(row, 0).toString());

            String sql = "DELETE FROM tbl_packages WHERE p_id = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, id);
            pst.executeUpdate();

            conn.close();

            JOptionPane.showMessageDialog(this, "Package deleted successfully!");
            displayPackage();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    }//GEN-LAST:event_deletepackageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        displayPackage();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonClicksearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClicksearchActionPerformed
          String keyword = jTextFieldSearchbar.getText().trim();

    if (keyword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter something to search!");
        return;
    }

    config conf = new config();
    String sql =
    "SELECT p_id, package_name, price, pax, description, status FROM tbl_packages " +
    "WHERE package_name LIKE '%" + keyword + "%' " +
    "OR price LIKE '%" + keyword + "%' " +
    "OR pax LIKE '%" + keyword + "%' " +  // NEW
    "OR description LIKE '%" + keyword + "%'";


    conf.displayUser(sql, table_package);
    }//GEN-LAST:event_jButtonClicksearchActionPerformed

    private void jButton3ReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ReservationsActionPerformed
        ReservationsTable rf = new ReservationsTable();
        rf.setVisible(true);
        rf.pack();
        rf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton3ReservationsActionPerformed

    private void jButton1ViewUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ViewUsersActionPerformed
        UsersTable utbl = new UsersTable();
        utbl.setVisible(true);
        utbl.pack();
        utbl.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ViewUsersActionPerformed

    private void UserProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserProfileActionPerformed
        UsersProfile2 users = new UsersProfile2();
        users.setVisible(true);
        users.pack();
        users.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_UserProfileActionPerformed

    private void jTextFieldSearchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchbarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PackagesTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PackagesTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PackagesTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PackagesTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PackagesTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UserProfile;
    private javax.swing.JButton addPackage;
    private javax.swing.JButton deletepackage;
    private javax.swing.JButton editpackage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1ViewUsers;
    private javax.swing.JButton jButton3Reservations;
    private javax.swing.JButton jButton4Packages;
    private javax.swing.JButton jButton5dashboard;
    private javax.swing.JButton jButtonClicksearch;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldSearchbar;
    private javax.swing.JButton logout;
    private javax.swing.JTable table_package;
    // End of variables declaration//GEN-END:variables
}
