/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import config.config;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class PaymentForm extends javax.swing.JDialog {

    private int reservationId;
    public PaymentForm(java.awt.Frame parent, boolean modal) {
         super(parent, modal);
    initComponents();
   
    
    }
    // NEW constructor with reservationId
    public PaymentForm(java.awt.Frame parent, boolean modal, int reservationId) {
        super(parent, modal);
        initComponents();
        this.reservationId = reservationId;

        // Load reservation details if needed
        loadReservationDetails();
    }
   private void loadReservationDetails() {
        try (Connection conn = config.connectDB();
             PreparedStatement pst = conn.prepareStatement(
                     "SELECT r.*, p.package_name, p.price FROM tbl_reservations r " +
                     "JOIN tbl_packages p ON r.p_id = p.p_id " +
                     "WHERE r.r_id = ?")) {

            pst.setInt(1, reservationId);
            try (ResultSet rs = pst.executeQuery()) {
                if (rs.next()) {
                    txtpackage_name.setText(rs.getString("package_name"));
                    txtPrice.setText(rs.getString("price"));
                    txtGuests.setText(rs.getString("num_guests"));
                    txtevent_date.setText(rs.getString("event_date"));
                    txtVenue.setText(rs.getString("venue"));
                    txtStatus.setText(rs.getString("status"));
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtpackage_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtGuests = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        txtevent_date = new javax.swing.JTextField();
        txtVenue = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        jButton1PAY = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtpackage_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 118, -1));

        jLabel1.setText("Event Date: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));
        jPanel1.add(txtGuests, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 118, -1));
        jPanel1.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 118, -1));
        jPanel1.add(txtevent_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 118, -1));
        jPanel1.add(txtVenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 118, -1));

        txtStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusActionPerformed(evt);
            }
        });
        jPanel1.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 118, -1));

        jButton1PAY.setText("PAY");
        jButton1PAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1PAYActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1PAY, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusActionPerformed

    private void jButton1PAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1PAYActionPerformed
         try (Connection conn = config.connectDB();
             PreparedStatement pst = conn.prepareStatement(
                     "UPDATE tbl_reservations SET status='PAID' WHERE r_id=?")) {

            pst.setInt(1, reservationId);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Payment Successful!");
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1PAYActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PaymentForm dialog = new PaymentForm(new javax.swing.JFrame(), true, 1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1PAY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtGuests;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtVenue;
    private javax.swing.JTextField txtevent_date;
    private javax.swing.JTextField txtpackage_name;
    // End of variables declaration//GEN-END:variables
}
