/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import config.config;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JSpinner.DateEditor;
import javax.swing.SpinnerDateModel;

public class ReservationForm extends javax.swing.JDialog {

      private int packageId;
    public ReservationForm(java.awt.Frame parent, boolean modal, int packageId) {
        super(parent, modal);
        initComponents();
        
        // Create a SpinnerDateModel
SpinnerDateModel timeModel = new SpinnerDateModel();

// Create a spinner model with current time
JSpinner jSpinnerTime = new JSpinner(timeModel);

// Set editor to show only hours and minutes with AM/PM
// Format spinner to show 12-hour time with AM/PM
JSpinner.DateEditor timeEditor = new JSpinner.DateEditor(jSpinnerTime, "hh:mm a");
jSpinnerTime.setEditor(timeEditor);
 // Set default value to current time
jSpinnerTime.setValue(new Date());
        this.packageId = packageId;
        loadPackageDetails();
        setLocationRelativeTo(parent);
  // Set default value to current time

    }

   
    private void loadPackageDetails() {
    // Use try-with-resources so connection automatically closes
    try (java.sql.Connection conn = config.connectDB();
         java.sql.PreparedStatement pst = conn.prepareStatement("SELECT * FROM tbl_packages WHERE p_id = ?")) {

        pst.setInt(1, packageId);

        try (java.sql.ResultSet rs = pst.executeQuery()) {
            if (rs.next()) {
                jTextFieldpackage_name.setText(rs.getString("package_name"));
                jTextFieldprice.setText(rs.getString("price"));
                jTextAreadescription.setText(rs.getString("description"));
                jTextFieldpax.setText(rs.getString("pax"));
            }
        }

        // Make fields read-only
        jTextFieldpackage_name.setEditable(false);
        jTextFieldprice.setEditable(false);
        jTextAreadescription.setEditable(false);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonReserve = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldpackage_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldprice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreadescription = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldvenue = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxEventType = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaRequest = new javax.swing.JTextArea();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jTextFieldguets = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldphone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSpinnerdownpayment = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxpayment_method = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jSpinnerTime = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldpax = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonReserve.setBackground(new java.awt.Color(0, 204, 204));
        jButtonReserve.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonReserve.setText("RESERVE");
        jButtonReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReserveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 200, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Event Type:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Special Request:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));

        jTextFieldpackage_name.setEnabled(false);
        jTextFieldpackage_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldpackage_nameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldpackage_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 160, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Description:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jTextFieldprice.setEnabled(false);
        jPanel1.add(jTextFieldprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 160, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Package Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jTextAreadescription.setColumns(20);
        jTextAreadescription.setRows(5);
        jTextAreadescription.setEnabled(false);
        jScrollPane1.setViewportView(jTextAreadescription);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 160, 110));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Price:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, 20));
        jPanel1.add(jTextFieldvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 160, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Guests:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        jComboBoxEventType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wedding", "Fiesta", "Birthday", "Corporate", " " }));
        jPanel1.add(jComboBoxEventType, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 160, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Event Time:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Event Date:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Venue:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        jTextAreaRequest.setColumns(20);
        jTextAreaRequest.setRows(5);
        jScrollPane2.setViewportView(jTextAreaRequest);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 170, 110));
        jPanel1.add(jDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 160, -1));
        jPanel1.add(jTextFieldguets, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 160, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Reservation Form ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));
        jPanel1.add(jTextFieldphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 160, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Phone Number:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));
        jPanel1.add(jSpinnerdownpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 160, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("DownPayment:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));

        jComboBoxpayment_method.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pay Maya", "Gcash", " " }));
        jPanel1.add(jComboBoxpayment_method, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 160, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Payment Method:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, -1, -1));

        jSpinnerTime.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), new java.util.Date(), java.util.Calendar.AM_PM));
        jPanel1.add(jSpinnerTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 160, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Pax:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        jTextFieldpax.setEnabled(false);
        jPanel1.add(jTextFieldpax, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReserveActionPerformed
        // Collect input values
    String eventType = jComboBoxEventType.getSelectedItem().toString();
    
    Date selectedTime = (Date) jSpinnerTime.getValue();
SimpleDateFormat sdf = new SimpleDateFormat("hh:mm a");
String timeString = sdf.format(selectedTime);
System.out.println("Selected time: " + timeString);
    int guests = (Integer) jTextFieldguets.getValue(); // Spinner value
    String venue = jTextFieldvenue.getText().trim();
    String specialRequest = jTextAreaRequest.getText().trim();
    String phone = jTextFieldphone.getText().trim();
    int downpayment = (Integer) jSpinnerdownpayment.getValue(); // Spinner value
    String paymentMethod = jComboBoxpayment_method.getSelectedItem().toString();

    // Validate required fields
    if (jDateChooser.getDate() == null || timeString.isEmpty() || venue.isEmpty() || phone.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all required fields!");
        return;
    }
    System.out.println("INSERTING USER ID: " + Session.u_id);
    try (Connection conn = config.connectDB();
         PreparedStatement pst = conn.prepareStatement (
                 "INSERT INTO tbl_reservations " +
                 "(u_id, p_id, event_type, event_time, event_date, num_guests, venue, special_request, phone, downpayment, payment_method, status) " +
                 "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'PENDING')")) {

        // Format date
        java.util.Date selectedDate = jDateChooser.getDate();
        java.text.SimpleDateFormat pdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String formattedDate = pdf.format(selectedDate);

        // Set parameters
        pst.setInt(1, Session.u_id);
        pst.setInt(2, packageId);
        pst.setString(3, eventType);
        pst.setString(4, timeString);
        pst.setString(5, formattedDate);
        pst.setInt(6, guests);
        pst.setString(7, venue);
        pst.setString(8, specialRequest);
        pst.setString(9, phone);
        pst.setInt(10, downpayment);
        pst.setString(11, paymentMethod);

        // Execute insertion
        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Reservation submitted successfully!");
        this.dispose();
        new ViewReservationTable().setVisible(true);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    
    }//GEN-LAST:event_jButtonReserveActionPerformed

    private void jTextFieldpackage_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldpackage_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldpackage_nameActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       // 🔐 CHECK LOGIN FIRST
    if (Session.u_id == 0) {

        JOptionPane.showMessageDialog(this, "Please login first!");

        // Open login form
        LoginForm login = new LoginForm();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);

        // Close this dashboard immediately
        this.dispose();
        return;
    }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReservationForm dialog = new ReservationForm(new javax.swing.JFrame(), true, 1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                        
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReserve;
    private javax.swing.JComboBox<String> jComboBoxEventType;
    private javax.swing.JComboBox<String> jComboBoxpayment_method;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerTime;
    private javax.swing.JSpinner jSpinnerdownpayment;
    private javax.swing.JTextArea jTextAreaRequest;
    private javax.swing.JTextArea jTextAreadescription;
    private javax.swing.JSpinner jTextFieldguets;
    private javax.swing.JTextField jTextFieldpackage_name;
    private javax.swing.JTextField jTextFieldpax;
    private javax.swing.JTextField jTextFieldphone;
    private javax.swing.JTextField jTextFieldprice;
    private javax.swing.JTextField jTextFieldvenue;
    // End of variables declaration//GEN-END:variables
}
