/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import config.config;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class ReservationForm extends javax.swing.JDialog {

      private int packageId;
    public ReservationForm(java.awt.Frame parent, boolean modal, int packageId) {
        super(parent, modal);
        initComponents();
        this.packageId = packageId;
        setLocationRelativeTo(parent);
        loadPackageDetails(); // 👈 load selected package
    }

   
    private void loadPackageDetails() {
    // Use try-with-resources so connection automatically closes
    try (java.sql.Connection conn = config.connectDB();
         java.sql.PreparedStatement pst = conn.prepareStatement("SELECT * FROM tbl_packages WHERE p_id = ?")) {

        pst.setInt(1, packageId);

        try (java.sql.ResultSet rs = pst.executeQuery()) {
            if (rs.next()) {
                jTextFieldpackage_name.setText(rs.getString("package_name"));
                jTextFieldprice.setText(rs.getString("price"));
                jTextAreadescription.setText(rs.getString("description"));
            }
        }

        // Make fields read-only
        jTextFieldpackage_name.setEditable(false);
        jTextFieldprice.setEditable(false);
        jTextAreadescription.setEditable(false);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        eventdate = new javax.swing.JTextField();
        jButtonReserve = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldguets = new javax.swing.JTextField();
        jTextFieldpackage_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldprice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreadescription = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldvenue = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxEventType = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldTime = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaRequest = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(eventdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 130, -1));

        jButtonReserve.setText("RESERVE");
        jButtonReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReserveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, -1, -1));

        jLabel1.setText("Event Type:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, 20));

        jLabel2.setText("Special Request:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        jTextFieldguets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldguetsActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldguets, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 130, -1));

        jTextFieldpackage_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldpackage_nameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldpackage_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 120, -1));

        jLabel3.setText("Description:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));
        jPanel1.add(jTextFieldprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 120, -1));

        jLabel4.setText("Package Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jTextAreadescription.setColumns(20);
        jTextAreadescription.setRows(5);
        jScrollPane1.setViewportView(jTextAreadescription);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 140, 80));

        jLabel5.setText("Price:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, 20));
        jPanel1.add(jTextFieldvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 130, -1));

        jLabel6.setText("Guests:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        jComboBoxEventType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wedding", "Fiesta", "Birthday", "Corporate", " " }));
        jPanel1.add(jComboBoxEventType, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 140, -1));

        jLabel7.setText("Event Time:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 20));

        jLabel8.setText("Event Date:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, 20));

        jTextFieldTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTimeActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 130, -1));

        jLabel9.setText("Venue:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        jTextAreaRequest.setColumns(20);
        jTextAreaRequest.setRows(5);
        jScrollPane2.setViewportView(jTextAreaRequest);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 140, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReserveActionPerformed
       String eventType = jComboBoxEventType.getSelectedItem().toString();
    String eventTime = jTextFieldTime.getText().trim();
    String eventDate = eventdate.getText().trim();
    String guests = jTextFieldguets.getText().trim();
    String venue = jTextFieldvenue.getText().trim();
    String specialRequest = jTextAreaRequest.getText().trim();

    if (eventDate.isEmpty() || eventTime.isEmpty() || guests.isEmpty() || venue.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all required fields!");
        return;
    }

    try (Connection conn = config.connectDB();
         PreparedStatement pst = conn.prepareStatement(
             "INSERT INTO tbl_reservations " +
             "(u_id, p_id, event_type, event_time, event_date, num_guests, venue, special_request, status) " +
             "VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'PENDING')")) {

        pst.setInt(1, Session.u_id);
        pst.setInt(2, packageId);
        pst.setString(3, eventType);
        pst.setString(4, eventTime);
        pst.setString(5, eventDate);
        pst.setInt(6, Integer.parseInt(guests));
        pst.setString(7, venue);
        pst.setString(8, specialRequest);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Reservation submitted!");
       this.dispose();
new ViewReservationTable().setVisible(true);


    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Guests must be a number!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jButtonReserveActionPerformed

    private void jTextFieldguetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldguetsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldguetsActionPerformed

    private void jTextFieldpackage_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldpackage_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldpackage_nameActionPerformed

    private void jTextFieldTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReservationForm dialog = new ReservationForm(new javax.swing.JFrame(), true, 1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eventdate;
    private javax.swing.JButton jButtonReserve;
    private javax.swing.JComboBox<String> jComboBoxEventType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaRequest;
    private javax.swing.JTextArea jTextAreadescription;
    private javax.swing.JTextField jTextFieldTime;
    private javax.swing.JTextField jTextFieldguets;
    private javax.swing.JTextField jTextFieldpackage_name;
    private javax.swing.JTextField jTextFieldprice;
    private javax.swing.JTextField jTextFieldvenue;
    // End of variables declaration//GEN-END:variables
}
