/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.io.File;
import javax.swing.JFileChooser;
/**
 *
 * @author Admin
 */
public class UsersProfile2 extends javax.swing.JFrame {
    private String selectedProfileImagePath = null; // temporary path before saving
    private void setProfileImage(String path) {
    
    ImageIcon icon = new ImageIcon(path);
    
    int width = 100;
    int height = 100;
    
    Image img = icon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
    lblProfileImage.setIcon(new ImageIcon(img));
    lblProfileImage.revalidate();
    lblProfileImage.repaint(
    
    );
  }


    /**
     * Creates new form UsersProfile
     */
    public UsersProfile2() {
        initComponents();
        loadUserProfile();
        jButtonupdateprofile.addActionListener(e -> updateUserProfile());
        
    // Delay image scaling until UI is ready
    java.awt.EventQueue.invokeLater(() -> {
        File file = new File("src/images/logo.jpg");
                System.out.println(file.exists()); // true or false

    });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
  private void loadUserProfile() {
    try {
        Connection con = new config.config().connectDB();
        String sql = "SELECT u_id, fullname, email, type, status FROM tbl_accounts WHERE u_id = ?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setInt(1, Session.u_id);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            jTextFieldID.setText(rs.getString("u_id"));
            jTextFieldfullname.setText(rs.getString("fullname"));
            jTextFieldemail.setText(rs.getString("email"));
            jTextFieldtype.setText(rs.getString("type"));
            jTextFieldstatus.setText(rs.getString("status"));

            // ✅ LOAD PROFILE IMAGE - search for any image with user ID prefix
            File profileDir = new File("src/images/profiles");
            File[] files = profileDir.listFiles();
            String userImagePath = null;
            
            if (files != null) {
                for (int i = 0; i < files.length; i++) {
                    File file = files[i];
                    String name = file.getName().toLowerCase();
                    
                    // Check if file starts with user ID and is an image
                    if (name.startsWith("user_" + Session.u_id + "_") && 
                        (name.endsWith(".jpg") || name.endsWith(".jpeg") || 
                         name.endsWith(".png") || name.endsWith(".gif") || 
                         name.endsWith(".bmp"))) {
                        userImagePath = file.getAbsolutePath();
                        break;
                    }
                }
            }
            
            if (userImagePath != null && new File(userImagePath).exists()) {
                setProfileImage(userImagePath);
            } else {
                // Default image from resources
                setProfileImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png")));
            }
        }
        con.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}
  private void updateUserProfile() {
    String fullname = jTextFieldfullname.getText().trim();
    String email = jTextFieldemail.getText().trim();

    if (fullname.isEmpty() || email.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all fields!", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        Connection con = new config.config().connectDB();

        // Get current values from database
        String getCurrentSql = "SELECT fullname, email FROM tbl_accounts WHERE u_id = ?";
        PreparedStatement getCurrentPst = con.prepareStatement(getCurrentSql);
        getCurrentPst.setInt(1, Session.u_id);
        ResultSet rs = getCurrentPst.executeQuery();

        if (rs.next()) {
            String currentFullname = rs.getString("fullname");
            String currentEmail = rs.getString("email");

            if (fullname.equals(currentFullname) && email.equals(currentEmail) && selectedProfileImagePath == null) {
                JOptionPane.showMessageDialog(this, "No changes detected!", "Info", JOptionPane.INFORMATION_MESSAGE);
                con.close();
                return;
            }
        }

        // Check if email already exists for another user
        String checkSql = "SELECT u_id FROM tbl_accounts WHERE email = ? AND u_id <> ?";
        PreparedStatement checkPst = con.prepareStatement(checkSql);
        checkPst.setString(1, email);
        checkPst.setInt(2, Session.u_id);

        ResultSet checkRs = checkPst.executeQuery();
        if (checkRs.next()) {
            JOptionPane.showMessageDialog(this, "Email already exists!", "Error", JOptionPane.ERROR_MESSAGE);
            con.close();
            return;
        }

        // ✅ SAVE PROFILE IMAGE - with original extension
        if (selectedProfileImagePath != null) {
            try {
                File source = new File(selectedProfileImagePath);
                String originalName = source.getName();
                String extension = "";
                
                int dotIndex = originalName.lastIndexOf('.');
                if (dotIndex > 0) {
                    extension = originalName.substring(dotIndex);
                }
                
                // Create directory if it doesn't exist
                File profileDir = new File("src/images/profiles");
                if (!profileDir.exists()) {
                    profileDir.mkdirs();
                }
                
                String destPath = "src/images/profiles/user_" + Session.u_id + "_profile" + extension;
                File dest = new File(destPath);
                
                // Delete old profile images first
                File[] oldFiles = profileDir.listFiles();
                if (oldFiles != null) {
                    for (File f : oldFiles) {
                        if (f.getName().startsWith("user_" + Session.u_id + "_")) {
                            f.delete();
                        }
                    }
                }
                
                java.nio.file.Files.copy(source.toPath(), dest.toPath(), 
                    java.nio.file.StandardCopyOption.REPLACE_EXISTING);
                
                selectedProfileImagePath = null; // Reset after saving
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error saving image: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        // Update fullname and email
        String sql = "UPDATE tbl_accounts SET fullname = ?, email = ? WHERE u_id = ?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, fullname);
        pst.setString(2, email);
        pst.setInt(3, Session.u_id);

        int updated = pst.executeUpdate();

        if (updated > 0) {
            JOptionPane.showMessageDialog(this, "Profile updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadUserProfile(); // Reload to show the saved image
        } else {
            JOptionPane.showMessageDialog(this, "Update failed.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
     
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        setProfileImage = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        UserProfile = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jButton5dashboard = new javax.swing.JButton();
        jButton4Packages = new javax.swing.JButton();
        jButton3Reservations = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldfullname = new javax.swing.JTextField();
        jTextFieldemail = new javax.swing.JTextField();
        jTextFieldtype = new javax.swing.JTextField();
        jTextFieldstatus = new javax.swing.JTextField();
        jButtonupdateprofile = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        setProfileImage.setBackground(new java.awt.Color(255, 255, 255));
        setProfileImage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        setProfileImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        setProfileImage.setOpaque(true);
        setProfileImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setProfileImageMouseClicked(evt);
            }
        });
        jPanel3.add(setProfileImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 130, 130));

        jLabelTitle.setBackground(new java.awt.Color(0, 153, 153));
        jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("User Profile");
        jLabelTitle.setOpaque(true);
        jPanel3.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 140, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User ID:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Type:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Status:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setText("View Users");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 140, -1));

        UserProfile.setBackground(new java.awt.Color(0, 153, 153));
        UserProfile.setText("Profile");
        UserProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserProfileActionPerformed(evt);
            }
        });
        jPanel2.add(UserProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 140, -1));

        logout.setBackground(new java.awt.Color(0, 153, 153));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel2.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 140, -1));

        jButton5dashboard.setBackground(new java.awt.Color(0, 153, 153));
        jButton5dashboard.setText("Dashboard");
        jButton5dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5dashboardActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 140, -1));

        jButton4Packages.setBackground(new java.awt.Color(0, 153, 153));
        jButton4Packages.setText("Packages");
        jButton4Packages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4PackagesActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4Packages, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 140, -1));

        jButton3Reservations.setBackground(new java.awt.Color(0, 153, 153));
        jButton3Reservations.setText("Reservations");
        jButton3Reservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ReservationsActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3Reservations, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 140, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/redefined.png"))); // NOI18N
        jLabel5.setOpaque(true);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 150));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 540));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Full Name:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Profile Picture:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        jTextFieldID.setEnabled(false);
        jPanel3.add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 130, -1));
        jPanel3.add(jTextFieldfullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 130, -1));
        jPanel3.add(jTextFieldemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 130, -1));

        jTextFieldtype.setEnabled(false);
        jPanel3.add(jTextFieldtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 130, -1));

        jTextFieldstatus.setEnabled(false);
        jPanel3.add(jTextFieldstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 130, -1));

        jButtonupdateprofile.setBackground(new java.awt.Color(0, 204, 204));
        jButtonupdateprofile.setText("Update Profile");
        jButtonupdateprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonupdateprofileActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonupdateprofile, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ReservationsActionPerformed
        ReservationsTable rf = new ReservationsTable();
        rf.setVisible(true);
        rf.pack();
        rf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton3ReservationsActionPerformed

    private void jButton4PackagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4PackagesActionPerformed
        PackagesTable pg = new PackagesTable();
        pg.setVisible(true);
        pg.pack();
        pg.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton4PackagesActionPerformed

    private void jButton5dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5dashboardActionPerformed
        // Already on dashboard
    }//GEN-LAST:event_jButton5dashboardActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (choice == JOptionPane.YES_OPTION) {

            // ✅ Clear session data
            Session.u_id = 0;
            Session.fullname = null;
            Session.type = null;

            // ✅ Go back to login
            LoginForm lgf = new LoginForm();
            lgf.setVisible(true);
            lgf.pack();
            lgf.setLocationRelativeTo(null);

            // ✅ Close current window
            this.dispose();
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void UserProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserProfileActionPerformed
        UsersProfile2 users = new UsersProfile2();
        users.setVisible(true);
        users.pack();
        users.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_UserProfileActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        UsersTable utbl = new UsersTable();
        utbl.setVisible(true);
        utbl.pack();
        utbl.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void setProfileImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setProfileImageMouseClicked

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select Profile Picture");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
            "Image files", "jpg", "jpeg", "png", "gif"
        ));

        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            ImageIcon icon = new ImageIcon(selectedFile.getAbsolutePath());

            // Scale image to fit JLabel
            Image img = icon.getImage().getScaledInstance(
                setProfileImage.getWidth(),
                setProfileImage.getHeight(),
                Image.SCALE_SMOOTH
            );
            setProfileImage.setIcon(new ImageIcon(img));
        }
    }//GEN-LAST:event_setProfileImageMouseClicked

    private void jButtonupdateprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonupdateprofileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonupdateprofileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersProfile2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersProfile2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersProfile2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersProfile2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersProfile2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UserProfile;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton3Reservations;
    private javax.swing.JButton jButton4Packages;
    private javax.swing.JButton jButton5dashboard;
    private javax.swing.JButton jButtonupdateprofile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldemail;
    private javax.swing.JTextField jTextFieldfullname;
    private javax.swing.JTextField jTextFieldstatus;
    private javax.swing.JTextField jTextFieldtype;
    private javax.swing.JButton logout;
    private javax.swing.JLabel setProfileImage;
    // End of variables declaration//GEN-END:variables

   

   
}


