/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import config.config;
import javax.swing.JOptionPane;

/**
 *
 * @author USER35
 */
public class UsersTable extends javax.swing.JFrame {

    /**
     * Creates new form UsersTable
     */
    public UsersTable() {
        initComponents();
         table_users.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        displayUser();
        
    }
    void displayUser() {
           config conf = new config();
           String sql = "SELECT u_id, fullname, email, type, status FROM tbl_accounts";
           conf.displayUser(sql, table_users);
           
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_users = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        UserProfile = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton5dashboard = new javax.swing.JButton();
        jButton4Packages = new javax.swing.JButton();
        jButton3Reservations = new javax.swing.JButton();
        jButtonAddUser = new javax.swing.JButton();
        jButtoneEditUser = new javax.swing.JButton();
        jButtonDeleteUser = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jTextFieldsearchbar = new javax.swing.JTextField();
        jButtonclicksearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table_users);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 640, 340));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("View Users");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 140, -1));

        UserProfile.setText("Profile");
        UserProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserProfileActionPerformed(evt);
            }
        });
        jPanel2.add(UserProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 140, -1));

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel2.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 140, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/catering (1).png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 130, 120));

        jButton5dashboard.setText("Dashboard");
        jButton5dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5dashboardActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 140, -1));

        jButton4Packages.setText("Packages");
        jButton4Packages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4PackagesActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4Packages, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 140, -1));

        jButton3Reservations.setText("Reservations");
        jButton3Reservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ReservationsActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3Reservations, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 140, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 510));

        jButtonAddUser.setText("ADD");
        jButtonAddUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAddUserMouseClicked(evt);
            }
        });
        jButtonAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddUserActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 90, -1));

        jButtoneEditUser.setText("EDIT");
        jButtoneEditUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtoneEditUserMouseClicked(evt);
            }
        });
        jButtoneEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneEditUserActionPerformed(evt);
            }
        });
        jPanel1.add(jButtoneEditUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 100, -1));

        jButtonDeleteUser.setText("DELETE ");
        jButtonDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteUserActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDeleteUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 90, -1));

        jButtonRefresh.setText("REFRESH");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 120, -1));
        jPanel1.add(jTextFieldsearchbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 180, -1));

        jButtonclicksearch.setText("SEARCH");
        jButtonclicksearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonclicksearchActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonclicksearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UsersTable utbl = new UsersTable();
        utbl.setVisible(true);
        utbl.pack();
        utbl.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void UserProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserProfileActionPerformed
        UsersProfile users = new UsersProfile();
        users.setVisible(true);
        users.pack();
        users.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_UserProfileActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (choice == JOptionPane.YES_OPTION) {

            // ✅ Clear session data
            Session.u_id = 0;
            Session.fullname = null;
            Session.type = null;

            // ✅ Go back to login
            LoginForm lgf = new LoginForm();
            lgf.setVisible(true);
            lgf.pack();
            lgf.setLocationRelativeTo(null);

            // ✅ Close current window
            this.dispose();
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        displayUser();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jButtonclicksearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonclicksearchActionPerformed
        String keyword = jTextFieldsearchbar.getText().trim();

    if (keyword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter something to search!");
        return;
    }

    config conf = new config();
    String sql =
        "SELECT u_id, fullname, email, type, status FROM tbl_accounts " +
        "WHERE fullname LIKE '%" + keyword + "%' " +
        "OR email LIKE '%" + keyword + "%' " +
        "OR type LIKE '%" + keyword + "%'";

    conf.displayUser(sql, table_users);
    }//GEN-LAST:event_jButtonclicksearchActionPerformed

    private void jButtonAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddUserActionPerformed
    UserForm form = new UserForm(this, true); // MODAL
    form.setVisible(true);

    // AUTO refresh when dialog closes
    displayUser();
    }//GEN-LAST:event_jButtonAddUserActionPerformed

    private void jButtoneEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneEditUserActionPerformed
    // Get selected row index
    int row = table_users.getSelectedRow();

    // If no row is selected, show message and stop
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a user first!");
        return; // exit the method
    }

    // Row is selected → get the user ID (u_id)
    int userId = Integer.parseInt(table_users.getValueAt(row, 0).toString());

    // Open UserForm in EDIT mode
    UserForm form = new UserForm(this, true);
    form.setFormMode(userId); // This loads the existing data
    form.setVisible(true);     // Show the form

    // Refresh table after closing the form
    displayUser();

       
    }//GEN-LAST:event_jButtoneEditUserActionPerformed

    private void jButtonDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteUserActionPerformed
       int row = table_users.getSelectedRow();

    // 1️⃣ Force user to select first
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a user first!");
        return;
    }

    // 2️⃣ Get selected user ID (u_id)
    int userId = Integer.parseInt(table_users.getValueAt(row, 0).toString());

    // 3️⃣ Confirm delete
    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to delete this user?",
        "Confirm Delete",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    // 4️⃣ Delete from database
    try {
        config conf = new config();
        String sql = "DELETE FROM tbl_accounts WHERE u_id = ?";
        int result = conf.executeUpdate(sql, userId);

        if (result > 0) {
            JOptionPane.showMessageDialog(this, "User deleted successfully!");
            displayUser(); // refresh table
        } else {
            JOptionPane.showMessageDialog(this, "Delete failed!");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_jButtonDeleteUserActionPerformed

    private void jButtonAddUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddUserMouseClicked
        UserForm uf = new UserForm(this, true);
uf.setFormMode(0); // ADD
uf.setVisible(true);

    }//GEN-LAST:event_jButtonAddUserMouseClicked

    private void jButtoneEditUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtoneEditUserMouseClicked
        int row = table_users.getSelectedRow();

if (row == -1) {
    JOptionPane.showMessageDialog(null, "Please select a user first");
    return;
}

int id = Integer.parseInt(table_users.getValueAt(row, 0).toString());

UserForm uf = new UserForm(this, true);
uf.setFormMode(id); // EDIT
uf.setVisible(true);

    }//GEN-LAST:event_jButtoneEditUserMouseClicked

    private void jButton5dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5dashboardActionPerformed
       
    }//GEN-LAST:event_jButton5dashboardActionPerformed

    private void jButton4PackagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4PackagesActionPerformed
        PackagesTable pg = new PackagesTable();
        pg.setVisible(true);
        pg.pack();
        pg.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton4PackagesActionPerformed

    private void jButton3ReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ReservationsActionPerformed
        ReservationsTable rf = new ReservationsTable();
        rf.setVisible(true);
        rf.pack();
        rf.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton3ReservationsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UserProfile;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3Reservations;
    private javax.swing.JButton jButton4Packages;
    private javax.swing.JButton jButton5dashboard;
    private javax.swing.JButton jButtonAddUser;
    private javax.swing.JButton jButtonDeleteUser;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonclicksearch;
    private javax.swing.JButton jButtoneEditUser;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldsearchbar;
    private javax.swing.JButton logout;
    private javax.swing.JTable table_users;
    // End of variables declaration//GEN-END:variables
}
