/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.io.File;
import javax.swing.JFileChooser;
/**
 *
 * @author Admin
 */
public class UsersProfile extends javax.swing.JFrame {
   
    private void setProfileImage(String path) {
    ImageIcon icon = new ImageIcon(path);

    Image img = icon.getImage().getScaledInstance(
            setProfileImage.getWidth(),
            setProfileImage.getHeight(),
            Image.SCALE_SMOOTH
    );

    setProfileImage.setIcon(new ImageIcon(img));
}

    /**
     * Creates new form UsersProfile
     */
    public UsersProfile() {
        initComponents();
        loadProfile();
        
    // Delay image scaling until UI is ready
    java.awt.EventQueue.invokeLater(() -> {
        setProfileImage("src/images/default.png");
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void loadProfile() {
    try {
        Connection con = new config.config().connectDB();
        String sql = "SELECT * FROM tbl_accounts WHERE u_id = ?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setInt(1, Session.userId);

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            usernameField.setText(rs.getString("username"));
       
            emailField.setText(rs.getString("email"));
            numberField.setText(rs.getString("phone number"));
            
           

            String imgPath = rs.getString("profile_image");
            if (imgPath != null) {
                setProfileImage(imgPath);
            }
        }

        con.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        fullnameField = new javax.swing.JTextField();
        setProfileImage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numberField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        updateProfile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        fullnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameFieldActionPerformed(evt);
            }
        });
        jPanel3.add(fullnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 160, 20));

        setProfileImage.setBackground(new java.awt.Color(255, 255, 255));
        setProfileImage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        setProfileImage.setText(" My Profile");
        setProfileImage.setOpaque(true);
        setProfileImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setProfileImageMouseClicked(evt);
            }
        });
        jPanel3.add(setProfileImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 160, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Full Name:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Phone Number:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));
        jPanel3.add(numberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 160, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Email:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        jPanel3.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 160, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Username:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));
        jPanel3.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 160, 20));

        jButton1.setText("Change Password");
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 120, -1));

        updateProfile.setText("Update Profile");
        updateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProfileActionPerformed(evt);
            }
        });
        jPanel3.add(updateProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfileActionPerformed
      
    try {
            Connection con = new config.config().connectDB();

            String sql = "UPDATE tbl_accounts SET username=?, email=? WHERE u_id=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, usernameField.getText());
            pst.setString(2, emailField.getText());
            pst.setInt(3, Session.userId);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Profile updated!");

            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


    }//GEN-LAST:event_updateProfileActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void fullnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameFieldActionPerformed

    private void setProfileImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setProfileImageMouseClicked
        
      

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(this);

        File file = chooser.getSelectedFile();
        if (file == null) return;

        try {
            Connection con = new config.config().connectDB();

            String sql = "UPDATE tbl_accounts SET profile_image=? WHERE u_id=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, file.getAbsolutePath());
            pst.setInt(2, Session.userId);
            pst.executeUpdate();

            setProfileImage(file.getAbsolutePath());

            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    
    

    }//GEN-LAST:event_setProfileImageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField fullnameField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField numberField;
    private javax.swing.JLabel setProfileImage;
    private javax.swing.JButton updateProfile;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables

   

   
}


