/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import static Main.Session.email;
import config.config;
import static config.config.connectDB;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author USER35
 */
public class UserForm extends javax.swing.JDialog {
public int u_id = 0; // 0 = ADD, >0 = UPDATE
    public UserForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);

    // Default Role options
        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "CUSTOMER", "STAFF" }));
        jComboBoxType.setSelectedIndex(1); // default CUSTOMER

        // Default Status options
        jComboBoxstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "APPROVED", "PENDING", "REJECTED" }));
        jComboBoxstatus.setSelectedIndex(0);
    


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldfullname = new javax.swing.JTextField();
        jLabelusername = new javax.swing.JLabel();
        jLabelemail = new javax.swing.JLabel();
        add = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        jTextFieldemail = new javax.swing.JTextField();
        jLabelemail1 = new javax.swing.JLabel();
        jLabeltype1 = new javax.swing.JLabel();
        jComboBoxstatus = new javax.swing.JComboBox<>();
        jTextFieldpassword = new javax.swing.JTextField();
        jComboBoxType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextFieldfullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 200, 30));

        jLabelusername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelusername.setText("Full Name:");
        jPanel1.add(jLabelusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabelemail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelemail.setForeground(new java.awt.Color(51, 51, 51));
        jLabelemail.setText("Password:");
        jPanel1.add(jLabelemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel.setText("Label");
        add.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 50, 20));

        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 200, 40));
        jPanel1.add(jTextFieldemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 200, 30));

        jLabelemail1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelemail1.setForeground(new java.awt.Color(51, 51, 51));
        jLabelemail1.setText("Email:");
        jPanel1.add(jLabelemail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jLabeltype1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabeltype1.setForeground(new java.awt.Color(51, 51, 51));
        jLabeltype1.setText("Status:");
        jPanel1.add(jLabeltype1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jComboBoxstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "APPROVED", "PENDING", "REJECT" }));
        jPanel1.add(jComboBoxstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 200, 40));
        jPanel1.add(jTextFieldpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 200, 30));

        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "CUSTOMER", "STAFF" }));
        jPanel1.add(jComboBoxType, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 200, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("User Form");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Role:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void loadUserData(int id) {
    String sql = "SELECT * FROM tbl_accounts WHERE u_id=?";

    try (Connection con = config.connectDB();
         PreparedStatement pst = con.prepareStatement(sql)) {

        pst.setInt(1, id);

        try (ResultSet rs = pst.executeQuery()) {
            if (rs.next()) {
                jTextFieldfullname.setText(rs.getString("fullname"));
                jTextFieldemail.setText(rs.getString("email"));
                jTextFieldpassword.setText(rs.getString("password"));
                jComboBoxType.setSelectedItem(rs.getString("type"));
                jComboBoxstatus.setSelectedItem(rs.getString("status"));
            }
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading user data: " + e.getMessage());
    }
}

    private void clearForm() {
    jTextFieldfullname.setText("");
    jTextFieldemail.setText("");
    jTextFieldpassword.setText("");
    jComboBoxType.setSelectedIndex(1); // Default CUSTOMER
    jComboBoxstatus.setSelectedIndex(0); // Default APPROVED
}


    public void setFormMode(int id) {
    this.u_id = id;

    if (u_id == 0) {
        jLabel.setText("ADD");
        clearForm();
    } else {
        jLabel.setText("UPDATE");
        loadUserData(u_id);
    }
}
private void addUser() {
    if (!validateForm()) return;

    String sql = "INSERT INTO tbl_accounts (fullname, email, password, type, status) VALUES (?, ?, ?, ?, ?)";

    try (Connection con = config.connectDB();
         PreparedStatement pst = con.prepareStatement(sql)) {

        pst.setString(1, jTextFieldfullname.getText().trim());
        pst.setString(2, jTextFieldemail.getText().trim());
        pst.setString(3, jTextFieldpassword.getText().trim());
        pst.setString(4, jComboBoxType.getSelectedItem().toString());
        pst.setString(5, jComboBoxstatus.getSelectedItem().toString());

        int result = pst.executeUpdate();

        if (result > 0) {
            JOptionPane.showMessageDialog(this, "User added successfully!");
            this.dispose(); // close form
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error adding user: " + e.getMessage());
    }
}

private void updateUser() {
    if (!validateForm()) return;

    String sql = "UPDATE tbl_accounts SET fullname=?, email=?, password=?, type=?, status=? WHERE u_id=?";

    try (Connection con = config.connectDB();
         PreparedStatement pst = con.prepareStatement(sql)) {

        pst.setString(1, jTextFieldfullname.getText().trim());
        pst.setString(2, jTextFieldemail.getText().trim());
        pst.setString(3, jTextFieldpassword.getText().trim());
        pst.setString(4, jComboBoxType.getSelectedItem().toString());
        pst.setString(5, jComboBoxstatus.getSelectedItem().toString());
        pst.setInt(6, u_id);

        int result = pst.executeUpdate();

        if (result > 0) {
            JOptionPane.showMessageDialog(this, "User updated successfully!");
            this.dispose(); // close form
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error updating user: " + e.getMessage());
    }
}



    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
     if (!validateForm()) return;

    if (u_id == 0) {
        addUser();
    } else {
        updateUser();
    }
    }//GEN-LAST:event_addMouseClicked
private boolean isEmailExists(String email) {

    String sql;

    // If adding new user
    if (u_id == 0) {
        sql = "SELECT * FROM tbl_accounts WHERE email = ?";
    } 
    // If updating user
    else {
        sql = "SELECT * FROM tbl_accounts WHERE email = ? AND u_id != ?";
    }

    try (Connection con = config.connectDB();
         PreparedStatement pst = con.prepareStatement(sql)) {

        pst.setString(1, email);

        if (u_id != 0) {
            pst.setInt(2, u_id);
        }

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            return true; // email already exists
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Email check error: " + e.getMessage());
    }

    return false;
}

    private boolean validateForm() {

    if (jTextFieldfullname.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Full name is required");
        return false;
    }

    if (jTextFieldemail.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Email is required");
    return false;
}

    if (jTextFieldpassword.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Password is required");
    return false;
}
    // ✅ CHECK DUPLICATE EMAIL
    if (isEmailExists(email)) {
        JOptionPane.showMessageDialog(this, "Email already exists. Please use another email.");
        return false;
    }


    

    return true;
}
    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserForm dialog = new UserForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JComboBox<String> jComboBoxstatus;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelemail;
    private javax.swing.JLabel jLabelemail1;
    private javax.swing.JLabel jLabeltype1;
    private javax.swing.JLabel jLabelusername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldemail;
    private javax.swing.JTextField jTextFieldfullname;
    private javax.swing.JTextField jTextFieldpassword;
    // End of variables declaration//GEN-END:variables

   

   
}
