/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import config.config;
import static config.config.connectDB;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author USER35
 */
public class UserForm extends javax.swing.JDialog {
public int userId = 0; // 0 = ADD, >0 = UPDATE
    public UserForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);

    // 1️⃣ Set sex radio buttons to be exclusive
    buttonGroup1.add(jRadioButtonmale);
    buttonGroup1.add(jRadioButtonfemale);

    // 2️⃣ Set status combo box choices
    jComboBoxstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
        "Single", "Married", "Widowed"
    }));

    jComboBoxstatus.setSelectedIndex(0);
    // Role

    // User Type
jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(
    new String[] { "ADMIN", "CUSTOMER", "STAFF" }
));
jComboBoxType.setSelectedIndex(1); // default CUSTOMER

// Account Status (Approved only)
jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(
    new String[] { "APPROVED" }
));
jComboBox1.setSelectedIndex(0);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldfullname = new javax.swing.JTextField();
        jLabelstatus = new javax.swing.JLabel();
        jLabelusername = new javax.swing.JLabel();
        jLabelemail = new javax.swing.JLabel();
        jLabeladdress = new javax.swing.JLabel();
        jRadioButtonfemale = new javax.swing.JRadioButton();
        jRadioButtonmale = new javax.swing.JRadioButton();
        jLabeltype = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaaddress = new javax.swing.JTextArea();
        jLabelsex = new javax.swing.JLabel();
        jComboBoxstatus = new javax.swing.JComboBox<>();
        jLabelimage = new javax.swing.JLabel();
        jLabelprofileimage = new javax.swing.JLabel();
        jTextFieldcontatc = new javax.swing.JTextField();
        add = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        jTextFieldemail = new javax.swing.JTextField();
        jLabelemail1 = new javax.swing.JLabel();
        jLabeltype1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabeltype2 = new javax.swing.JLabel();
        jTextFieldpassword = new javax.swing.JTextField();
        jComboBoxType = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextFieldfullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 200, 30));

        jLabelstatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelstatus.setForeground(new java.awt.Color(51, 51, 51));
        jLabelstatus.setText("civil status:");
        jPanel1.add(jLabelstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabelusername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelusername.setForeground(new java.awt.Color(51, 51, 51));
        jLabelusername.setText("Full Name:");
        jPanel1.add(jLabelusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabelemail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelemail.setForeground(new java.awt.Color(51, 51, 51));
        jLabelemail.setText("Password:");
        jPanel1.add(jLabelemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabeladdress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabeladdress.setForeground(new java.awt.Color(51, 51, 51));
        jLabeladdress.setText("Address:");
        jPanel1.add(jLabeladdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jRadioButtonfemale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonfemale.setText("Female");
        jPanel1.add(jRadioButtonfemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 70, 30));

        jRadioButtonmale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButtonmale.setText("Male");
        jPanel1.add(jRadioButtonmale, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 60, 30));

        jLabeltype.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabeltype.setForeground(new java.awt.Color(51, 51, 51));
        jLabeltype.setText("Role:");
        jPanel1.add(jLabeltype, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        jTextAreaaddress.setColumns(20);
        jTextAreaaddress.setRows(5);
        jScrollPane1.setViewportView(jTextAreaaddress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 200, 140));

        jLabelsex.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelsex.setForeground(new java.awt.Color(51, 51, 51));
        jLabelsex.setText("Sex:");
        jPanel1.add(jLabelsex, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jComboBoxstatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxstatus.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jComboBoxstatusComponentAdded(evt);
            }
        });
        jComboBoxstatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxstatusMouseClicked(evt);
            }
        });
        jComboBoxstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxstatusActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 200, 40));

        jLabelimage.setBackground(new java.awt.Color(255, 255, 255));
        jLabelimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jLabelimage.setOpaque(true);
        jLabelimage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelimageMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 170, 150));

        jLabelprofileimage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelprofileimage.setForeground(new java.awt.Color(51, 51, 51));
        jLabelprofileimage.setText("Picture:");
        jPanel1.add(jLabelprofileimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));
        jPanel1.add(jTextFieldcontatc, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 170, 30));

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel.setText("Label");
        add.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 50, 20));

        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 170, 40));
        jPanel1.add(jTextFieldemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 200, 30));

        jLabelemail1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelemail1.setForeground(new java.awt.Color(51, 51, 51));
        jLabelemail1.setText("Email:");
        jPanel1.add(jLabelemail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabeltype1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabeltype1.setForeground(new java.awt.Color(51, 51, 51));
        jLabeltype1.setText("Status:");
        jPanel1.add(jLabeltype1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Approved", " " }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 160, 40));

        jLabeltype2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabeltype2.setForeground(new java.awt.Color(51, 51, 51));
        jLabeltype2.setText("Contact:");
        jPanel1.add(jLabeltype2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));
        jPanel1.add(jTextFieldpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 200, 30));

        jComboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "CUSTOMER", "STAFF", " " }));
        jPanel1.add(jComboBoxType, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 170, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 623, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadUserData(int id) {
   String sql = "SELECT * FROM tbl_accounts WHERE u_id=?";

    try (Connection con = config.connectDB();
         PreparedStatement pst = con.prepareStatement(sql)) {

        pst.setInt(1, id);

        try (ResultSet rs = pst.executeQuery()) {
            if (rs.next()) {
                jTextFieldfullname.setText(rs.getString("fullname"));
                jTextFieldemail.setText(rs.getString("email"));
                jTextFieldpassword.setText(rs.getString("password"));
                jTextFieldcontatc.setText(rs.getString("contact"));
                jTextAreaaddress.setText(rs.getString("address"));
                jComboBoxstatus.setSelectedItem(rs.getString("civil_status"));
                jComboBoxType.setSelectedItem(rs.getString("type"));
                jComboBox1.setSelectedItem(rs.getString("status"));


                String sex = rs.getString("sex");
                if ("Male".equalsIgnoreCase(sex)) {
                    jRadioButtonmale.setSelected(true);
                } else {
                    jRadioButtonfemale.setSelected(true);
                }
            }
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
    private void clearForm() {
    jTextFieldfullname.setText("");
    jTextFieldpassword.setText("");
    jTextFieldcontatc.setText("");
    jTextAreaaddress.setText("");
    buttonGroup1.clearSelection();
    jComboBoxstatus.setSelectedIndex(0);
}

    public void setFormMode(int id) {
    this.userId = id;

    if (userId == 0) {
        jLabel.setText("ADD");
        clearForm();
    } else {
        jLabel.setText("UPDATE");
        loadUserData(userId);
    }
}
private void addUser() {

    if (!validateForm()) return;

    String sql = "INSERT INTO tbl_accounts "
            + "(fullname, email, password, sex, contact, civil_status, address, type, status) "
            + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

    try (Connection con = config.connectDB();
         PreparedStatement pst = con.prepareStatement(sql)) {

        pst.setString(1, jTextFieldfullname.getText());
        pst.setString(2, jTextFieldemail.getText());
        pst.setString(3, jTextFieldpassword.getText());
        pst.setString(4, jRadioButtonmale.isSelected() ? "Male" : "Female");
        pst.setString(5, jTextFieldcontatc.getText());
        pst.setString(6, jComboBoxstatus.getSelectedItem().toString());
        pst.setString(7, jTextAreaaddress.getText());
        pst.setString(8, jComboBoxType.getSelectedItem().toString());
        pst.setString(9, "APPROVED"); // Always approved

        int result = pst.executeUpdate();

        if (result > 0) {
            JOptionPane.showMessageDialog(this, "User added successfully!");
            this.dispose();
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}

private void updateUser() {

    if (!validateForm()) return;

    String sql = "UPDATE tbl_accounts SET "
            + "fullname=?, email=?, password=?, sex=?, contact=?, "
            + "civil_status=?, address=?, type=?, status=? "
            + "WHERE u_id=?";

    try (Connection con = config.connectDB();
         PreparedStatement pst = con.prepareStatement(sql)) {

        pst.setString(1, jTextFieldfullname.getText());
        pst.setString(2, jTextFieldemail.getText());
        pst.setString(3, jTextFieldpassword.getText());
        pst.setString(4, jRadioButtonmale.isSelected() ? "Male" : "Female");
        pst.setString(5, jTextFieldcontatc.getText());
        pst.setString(6, jComboBoxstatus.getSelectedItem().toString());
        pst.setString(7, jTextAreaaddress.getText());
        pst.setString(8, jComboBoxType.getSelectedItem().toString());
        pst.setString(9, "APPROVED"); // Always approved
        pst.setInt(10, userId);

        int result = pst.executeUpdate();

        if (result > 0) {
            JOptionPane.showMessageDialog(this, "User updated successfully!");
            this.dispose();
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}


    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
     if (!validateForm()) return;

    if (userId == 0) {
        addUser();
    } else {
        updateUser();
    }
    }//GEN-LAST:event_addMouseClicked

    private boolean validateForm() {

    if (jTextFieldfullname.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Full name is required");
        return false;
    }

    if (jTextFieldemail.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Email is required");
    return false;
}

    if (jTextFieldpassword.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Password is required");
    return false;
}


    if (!jRadioButtonmale.isSelected() && !jRadioButtonfemale.isSelected()) {
        JOptionPane.showMessageDialog(this, "Please select sex");
        return false;
    }

    if (jTextFieldcontatc.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Contact is required");
        return false;
    }

    return true;
}

    private void jComboBoxstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxstatusActionPerformed
      

    }//GEN-LAST:event_jComboBoxstatusActionPerformed

    private void jComboBoxstatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxstatusMouseClicked
       
    }//GEN-LAST:event_jComboBoxstatusMouseClicked

    private void jComboBoxstatusComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jComboBoxstatusComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxstatusComponentAdded

    private void jLabelimageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelimageMouseClicked
       JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select Profile Picture");
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
            "Image files", "jpg", "jpeg", "png", "gif"
        ));

        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            ImageIcon icon = new ImageIcon(selectedFile.getAbsolutePath());

            // Scale image to fit JLabel
            Image img = icon.getImage().getScaledInstance(
                    jLabelimage.getWidth(),
                    jLabelimage.getHeight(),
                    Image.SCALE_SMOOTH
            );
            jLabelimage.setIcon(new ImageIcon(img));
        }
    
    }//GEN-LAST:event_jLabelimageMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserForm dialog = new UserForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JComboBox<String> jComboBoxstatus;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabeladdress;
    private javax.swing.JLabel jLabelemail;
    private javax.swing.JLabel jLabelemail1;
    private javax.swing.JLabel jLabelimage;
    private javax.swing.JLabel jLabelprofileimage;
    private javax.swing.JLabel jLabelsex;
    private javax.swing.JLabel jLabelstatus;
    private javax.swing.JLabel jLabeltype;
    private javax.swing.JLabel jLabeltype1;
    private javax.swing.JLabel jLabeltype2;
    private javax.swing.JLabel jLabelusername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonfemale;
    private javax.swing.JRadioButton jRadioButtonmale;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaaddress;
    private javax.swing.JTextField jTextFieldcontatc;
    private javax.swing.JTextField jTextFieldemail;
    private javax.swing.JTextField jTextFieldfullname;
    private javax.swing.JTextField jTextFieldpassword;
    // End of variables declaration//GEN-END:variables

   

   
}
